<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Title</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>

<div class="add-category-item">

    <div class="item-form-block">
        <label for="itemForm" class="form-label">добавить товар:</label>
        <form action="/item/addItem" class="item-form" name="itemForm" method="post">
            <label for="itemName">названия товара:</label>
            <input type="text" name="itemName" placeholder="введите название товара" id="itemName">


            <label for="itemDescription">описания товара:</label>
            <textarea name="itemDescription" placeholder="введите описания товара" id="itemDescription"></textarea>

            <label for="itemCount">количества товара:</label>
            <input type="number" name="itemCount" placeholder="введите количество товара" value="1" id="itemCount">

            <label for="itemCategory">выберете категорию товара:</label>
            <select name="itemCategory" id="itemCategory">
                <?php foreach (categoryPrint() as $names) { ?>
                    <option value="<?php foreach ($names as $key => $name) {
                        if ($key == "id") {
                            echo trim($name);
                        }
                    } ?>"><?php foreach ($names as $key => $name) {
                            if ($key == "name") {
                                echo trim($name);
                            }
                        } ?></option>
                <?php } ?>
            </select>
            <input type="submit" value="добавить">
        </form>
    </div>

    <div class="category-form-block">
        <label for="categoryForm" class="form-label">добавить категорию:</label>
        <form action="/category/addCategory" class="category-form" name="categoryForm" method="post">
            <label for="categoryName"></label>
            <input type="text" name="categoryName" placeholder="введите название категории" id="categoryName">

            <input type="submit" value="добавить">
        </form>
    </div>
</div>

<label for="categoryLinks" class="form-label">доступные категории:</label>
<ol id="categoryLinks">
        <?php foreach (categoryPrint() as $names) { ?>
            <?php foreach ($names as $key => $name) { ?>

            <?php if ($key == 'name') { ?>
                    <li><a href="#"><?php echo "$name<br>"; ?></a></li>
                    <?php } ?>
        <?php } ?>
    <?php } ?>
</ol>

<script src="js/main.js"></script>

</body>
</html>